/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  AdminDeliverProposalDto,
  AdminProposalsControllerDeliverProposal200,
  AdminProposalsControllerGetProposalDetail200,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAdminProposals = () => {
  /**
   * Retrieves the complete proposal details including associated service request, organization, tender, team members, and past projects.
   * @summary Get proposal details for admin
   */
  const adminProposalsControllerGetProposalDetail = (
    id: string,
    options?: SecondParameter<typeof api<AdminProposalsControllerGetProposalDetail200>>,
  ) => {
    return api<AdminProposalsControllerGetProposalDetail200>(
      { url: `/api/admin-api/proposals/${id}`, method: "GET" },
      options,
    );
  };
  /**
   * Saves final updates to a proposal, marks its status as submitted, sets the associated service request to delivered, and notifies the client owner.
   * @summary Deliver / finalize a proposal
   */
  const adminProposalsControllerDeliverProposal = (
    id: string,
    adminDeliverProposalDto: AdminDeliverProposalDto,
    options?: SecondParameter<typeof api<AdminProposalsControllerDeliverProposal200>>,
  ) => {
    return api<AdminProposalsControllerDeliverProposal200>(
      {
        url: `/api/admin-api/proposals/${id}/deliver`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: adminDeliverProposalDto,
      },
      options,
    );
  };
  return { adminProposalsControllerGetProposalDetail, adminProposalsControllerDeliverProposal };
};
export type AdminProposalsControllerGetProposalDetailResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminProposals>["adminProposalsControllerGetProposalDetail"]>
  >
>;
export type AdminProposalsControllerDeliverProposalResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminProposals>["adminProposalsControllerDeliverProposal"]>
  >
>;
