/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  AdminProposalsControllerDeliverProposal200,
  AdminProposalsControllerGetProposalDetail200,
  AdminProposalsControllerGetProposalSections200,
  AdminProposalsControllerUpdateProposalSection200,
  UpdateProposalSectionDto,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAdminProposals = () => {
  /**
   * Retrieves the complete proposal details including associated service request, organization, tender, team members, and past projects.
   * @summary Get proposal details for admin
   */
  const adminProposalsControllerGetProposalDetail = (
    id: string,
    options?: SecondParameter<typeof api<AdminProposalsControllerGetProposalDetail200>>,
  ) => {
    return api<AdminProposalsControllerGetProposalDetail200>(
      { url: `/api/admin-api/proposals/${id}`, method: "GET" },
      options,
    );
  };
  /**
   * Saves final updates to a proposal, marks its status as submitted, sets the associated service request to delivered, and notifies the client owner.
   * @summary Deliver / finalize a proposal
   */
  const adminProposalsControllerDeliverProposal = (
    id: string,
    options?: SecondParameter<typeof api<AdminProposalsControllerDeliverProposal200>>,
  ) => {
    return api<AdminProposalsControllerDeliverProposal200>(
      { url: `/api/admin-api/proposals/${id}/deliver`, method: "PATCH" },
      options,
    );
  };
  /**
   * Retrieves all sections of a proposal for administrative review.
   * @summary Get all sections of a proposal for admin
   */
  const adminProposalsControllerGetProposalSections = (
    id: string,
    options?: SecondParameter<typeof api<AdminProposalsControllerGetProposalSections200>>,
  ) => {
    return api<AdminProposalsControllerGetProposalSections200>(
      { url: `/api/admin-api/proposals/${id}/sections`, method: "GET" },
      options,
    );
  };
  /**
   * Updates a specific section of a proposal for administrative review.
   * @summary Update a specific section of a proposal for admin
   */
  const adminProposalsControllerUpdateProposalSection = (
    id: string,
    sectionId: string,
    updateProposalSectionDto: UpdateProposalSectionDto,
    options?: SecondParameter<typeof api<AdminProposalsControllerUpdateProposalSection200>>,
  ) => {
    return api<AdminProposalsControllerUpdateProposalSection200>(
      {
        url: `/api/admin-api/proposals/${id}/sections/${sectionId}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateProposalSectionDto,
      },
      options,
    );
  };
  return {
    adminProposalsControllerGetProposalDetail,
    adminProposalsControllerDeliverProposal,
    adminProposalsControllerGetProposalSections,
    adminProposalsControllerUpdateProposalSection,
  };
};
export type AdminProposalsControllerGetProposalDetailResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminProposals>["adminProposalsControllerGetProposalDetail"]>
  >
>;
export type AdminProposalsControllerDeliverProposalResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminProposals>["adminProposalsControllerDeliverProposal"]>
  >
>;
export type AdminProposalsControllerGetProposalSectionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminProposals>["adminProposalsControllerGetProposalSections"]>
  >
>;
export type AdminProposalsControllerUpdateProposalSectionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAdminProposals>["adminProposalsControllerUpdateProposalSection"]
    >
  >
>;
