"use client";

import { useTendersControllerListTenders } from "@/lib/api/react-query/tenders/tenders";
import {
  TendersControllerListTendersStatus,
  TendersControllerListTendersSortBy,
} from "@/types/api";
import { useTranslations } from "next-intl";
import { useEffect, useState } from "react";
import TenderCard from "@/components/dashboard/tenders/TenderCard";
import TenderFilters from "@/components/dashboard/tenders/TenderFilters";
import TenderPagination from "@/components/dashboard/tenders/TenderPagination";

export default function TendersListPage() {
  const t = useTranslations("TendersList");
  const [page, setPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");

  // Filter states
  const [sector, setSector] = useState<string | undefined>(undefined);
  const [region, setRegion] = useState<string | undefined>(undefined);
  const [type, setType] = useState<string | undefined>(undefined);
  const [status, setStatus] = useState<TendersControllerListTendersStatus | undefined>(undefined);
  const [minBudget, setMinBudget] = useState<number | undefined>(undefined);
  const [maxBudget, setMaxBudget] = useState<number | undefined>(undefined);
  const [sortBy, setSortBy] = useState<TendersControllerListTendersSortBy | undefined>(undefined);

  // Debounce search query changes to avoid flooding the API
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearchQuery(searchQuery);
    }, 300);

    return () => {
      clearTimeout(handler);
    };
  }, [searchQuery]);

  // Fetching data via React Query hook generated by Orval
  const { data: response, isLoading } = useTendersControllerListTenders({
    page,
    limit: 10,
    keyword: debouncedSearchQuery || undefined,
    sector,
    region,
    type,
    status,
    minBudget,
    maxBudget,
    sortBy,
  });

  const tenders = response?.data || [];
  const totalCount = response?.meta?.total as number;
  const totalPages = (response?.meta?.totalPages as number) || 1;

  const handleFilterChange = () => {
    setPage(1);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="pt-0 pb-24 px-6 md:px-12 relative">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <h1 className="h2 ">{t("title")}</h1>
            {totalCount || totalCount === 0 ? (
              <p className="text-neutral-400">{t("subtitle", { count: totalCount })}</p>
            ) : (
              <p className="text-neutral-400">{t("loading")}</p>
            )}
          </div>
        </div>
      </div>

      {/* Main Content & Search Overlay */}
      <div className="max-w-7xl mx-auto px-6 md:px-12 -mt-16 relative z-10 space-y-6">
        <TenderFilters
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          sector={sector}
          setSector={setSector}
          region={region}
          setRegion={setRegion}
          type={type}
          setType={setType}
          status={status}
          setStatus={setStatus}
          minBudget={minBudget}
          setMinBudget={setMinBudget}
          maxBudget={maxBudget}
          setMaxBudget={setMaxBudget}
          sortBy={sortBy}
          setSortBy={setSortBy}
          onFilterChange={handleFilterChange}
        />

        {/* Tenders List */}
        <div className="space-y-4 pb-12">
          {isLoading ? (
            <div className="flex justify-center p-12">
              <span className="text-primary-800">{t("loading")}</span>
            </div>
          ) : tenders && tenders.length > 0 ? (
            tenders.map((tender) => <TenderCard key={tender.id} tender={tender} />)
          ) : (
            <div className="flex justify-center p-12">
              <span className="text-primary-800">{t("noResult")}</span>
            </div>
          )}
        </div>

        {/* Pagination Controls */}
        {!isLoading && tenders.length > 0 && (
          <TenderPagination page={page} setPage={setPage} totalPages={totalPages} />
        )}
      </div>
    </div>
  );
}
