/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { PythonAiControllerGenerateParams } from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Generate a section of the proposal
 * @summary Generate a section of the proposal
 */
export const pythonAiControllerGenerate = (
  projectId: string,
  section: string,
  params?: PythonAiControllerGenerateParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `/api/python-ai/${projectId}/generate/${section}`, method: "POST", params, signal },
    options,
  );
};

export const getPythonAiControllerGenerateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pythonAiControllerGenerate>>,
    TError,
    { projectId: string; section: string; params?: PythonAiControllerGenerateParams },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pythonAiControllerGenerate>>,
  TError,
  { projectId: string; section: string; params?: PythonAiControllerGenerateParams },
  TContext
> => {
  const mutationKey = ["pythonAiControllerGenerate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pythonAiControllerGenerate>>,
    { projectId: string; section: string; params?: PythonAiControllerGenerateParams }
  > = (props) => {
    const { projectId, section, params } = props ?? {};

    return pythonAiControllerGenerate(projectId, section, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PythonAiControllerGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof pythonAiControllerGenerate>>
>;

export type PythonAiControllerGenerateMutationError = void;

/**
 * @summary Generate a section of the proposal
 */
export const usePythonAiControllerGenerate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pythonAiControllerGenerate>>,
      TError,
      { projectId: string; section: string; params?: PythonAiControllerGenerateParams },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pythonAiControllerGenerate>>,
  TError,
  { projectId: string; section: string; params?: PythonAiControllerGenerateParams },
  TContext
> => {
  return useMutation(getPythonAiControllerGenerateMutationOptions(options), queryClient);
};
/**
 * Use tender and company profile to initialize a proposal
 * @summary Initialize a proposal
 */
export const pythonAiControllerInitialize = (
  projectId: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `/api/python-ai/${projectId}/initialize`, method: "POST", signal },
    options,
  );
};

export const getPythonAiControllerInitializeMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pythonAiControllerInitialize>>,
    TError,
    { projectId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pythonAiControllerInitialize>>,
  TError,
  { projectId: string },
  TContext
> => {
  const mutationKey = ["pythonAiControllerInitialize"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pythonAiControllerInitialize>>,
    { projectId: string }
  > = (props) => {
    const { projectId } = props ?? {};

    return pythonAiControllerInitialize(projectId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PythonAiControllerInitializeMutationResult = NonNullable<
  Awaited<ReturnType<typeof pythonAiControllerInitialize>>
>;

export type PythonAiControllerInitializeMutationError = void;

/**
 * @summary Initialize a proposal
 */
export const usePythonAiControllerInitialize = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pythonAiControllerInitialize>>,
      TError,
      { projectId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pythonAiControllerInitialize>>,
  TError,
  { projectId: string },
  TContext
> => {
  return useMutation(getPythonAiControllerInitializeMutationOptions(options), queryClient);
};
