/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  ExportControllerExportPdfParams,
  ExportControllerExportTestPdfParams,
  ExportControllerExportTestWordParams,
  ExportControllerExportWordParams,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getExport = () => {
  /**
   * Generates and downloads a dummy Word document for testing the export feature.
   * @summary Export test proposal as Word document
   */
  const exportControllerExportTestWord = (
    params?: ExportControllerExportTestWordParams,
    options?: SecondParameter<typeof api<unknown>>,
  ) => {
    return api<unknown>({ url: `/api/proposals/test-export/word`, method: "GET", params }, options);
  };
  /**
   * Generates and downloads a Word document for the given proposal.
   * @summary Export proposal as Word document
   */
  const exportControllerExportWord = (
    id: string,
    params?: ExportControllerExportWordParams,
    options?: SecondParameter<typeof api<unknown>>,
  ) => {
    return api<unknown>(
      { url: `/api/proposals/${id}/export/word`, method: "GET", params },
      options,
    );
  };
  /**
   * Generates and downloads a dummy PDF document for testing the export feature.
   * @summary Export test proposal as PDF document
   */
  const exportControllerExportTestPdf = (
    params?: ExportControllerExportTestPdfParams,
    options?: SecondParameter<typeof api<Blob>>,
  ) => {
    return api<Blob>(
      { url: `/api/proposals/test-export/pdf`, method: "GET", params, responseType: "blob" },
      options,
    );
  };
  /**
   * Generates and downloads a PDF document for the given proposal.
   * @summary Export proposal as PDF document
   */
  const exportControllerExportPdf = (
    id: string,
    params?: ExportControllerExportPdfParams,
    options?: SecondParameter<typeof api<Blob>>,
  ) => {
    return api<Blob>(
      { url: `/api/proposals/${id}/export/pdf`, method: "GET", params, responseType: "blob" },
      options,
    );
  };
  return {
    exportControllerExportTestWord,
    exportControllerExportWord,
    exportControllerExportTestPdf,
    exportControllerExportPdf,
  };
};
export type ExportControllerExportTestWordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExport>["exportControllerExportTestWord"]>>
>;
export type ExportControllerExportWordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExport>["exportControllerExportWord"]>>
>;
export type ExportControllerExportTestPdfResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExport>["exportControllerExportTestPdf"]>>
>;
export type ExportControllerExportPdfResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExport>["exportControllerExportPdf"]>>
>;
