/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PythonAiControllerGenerateParams } from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPythonAi = () => {
  /**
   * Generate a section of the proposal
   * @summary Generate a section of the proposal
   */
  const pythonAiControllerGenerate = (
    projectId: string,
    section: string,
    params?: PythonAiControllerGenerateParams,
    options?: SecondParameter<typeof api<void>>,
  ) => {
    return api<void>(
      { url: `/api/python-ai/${projectId}/generate/${section}`, method: "POST", params },
      options,
    );
  };
  /**
   * Use tender and company profile to initialize a proposal
   * @summary Initialize a proposal
   */
  const pythonAiControllerInitialize = (
    projectId: string,
    options?: SecondParameter<typeof api<void>>,
  ) => {
    return api<void>({ url: `/api/python-ai/${projectId}/initialize`, method: "POST" }, options);
  };
  return { pythonAiControllerGenerate, pythonAiControllerInitialize };
};
export type PythonAiControllerGenerateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPythonAi>["pythonAiControllerGenerate"]>>
>;
export type PythonAiControllerInitializeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPythonAi>["pythonAiControllerInitialize"]>>
>;
