/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponseDto,
  CreateDocumentDto,
  CreateOrganizationDto,
  CreateProjectDto,
  CreateTeamMemberDto,
  OrgDocumentResponseDto,
  OrganizationResponseDto,
  PastProjectResponseDto,
  TeamMemberResponseDto,
  UpdateOrganizationDto,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Register a new organization
 */
export const organizationsControllerCreate = (
  createOrganizationDto: CreateOrganizationDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<OrganizationResponseDto>(
    {
      url: `/api/organizations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createOrganizationDto,
      signal,
    },
    options,
  );
};

export const getOrganizationsControllerCreateMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerCreate>>,
    TError,
    { data: CreateOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerCreate>>,
  TError,
  { data: CreateOrganizationDto },
  TContext
> => {
  const mutationKey = ["organizationsControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerCreate>>,
    { data: CreateOrganizationDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerCreate>>
>;
export type OrganizationsControllerCreateMutationBody = CreateOrganizationDto;
export type OrganizationsControllerCreateMutationError = ApiErrorResponseDto;

/**
 * @summary Register a new organization
 */
export const useOrganizationsControllerCreate = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerCreate>>,
      TError,
      { data: CreateOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerCreate>>,
  TError,
  { data: CreateOrganizationDto },
  TContext
> => {
  return useMutation(getOrganizationsControllerCreateMutationOptions(options), queryClient);
};
/**
 * @summary Get current user's organization profile
 */
export const organizationsControllerGetMe = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<OrganizationResponseDto>(
    { url: `/api/organizations/me`, method: "GET", signal },
    options,
  );
};

export const getOrganizationsControllerGetMeQueryKey = () => {
  return [`/api/organizations/me`] as const;
};

export const getOrganizationsControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerGetMe>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsControllerGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerGetMe>>> = ({
    signal,
  }) => organizationsControllerGetMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerGetMe>>
>;
export type OrganizationsControllerGetMeQueryError = ApiErrorResponseDto;

export function useOrganizationsControllerGetMe<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMe>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerGetMe<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMe>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerGetMe<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMe>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current user's organization profile
 */

export function useOrganizationsControllerGetMe<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMe>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOrganizationsControllerGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update organization basic info
 */
export const organizationsControllerUpdateMe = (
  updateOrganizationDto: UpdateOrganizationDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<OrganizationResponseDto>(
    {
      url: `/api/organizations/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateOrganizationDto,
      signal,
    },
    options,
  );
};

export const getOrganizationsControllerUpdateMeMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerUpdateMe>>,
    TError,
    { data: UpdateOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerUpdateMe>>,
  TError,
  { data: UpdateOrganizationDto },
  TContext
> => {
  const mutationKey = ["organizationsControllerUpdateMe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerUpdateMe>>,
    { data: UpdateOrganizationDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerUpdateMe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerUpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerUpdateMe>>
>;
export type OrganizationsControllerUpdateMeMutationBody = UpdateOrganizationDto;
export type OrganizationsControllerUpdateMeMutationError = ApiErrorResponseDto;

/**
 * @summary Update organization basic info
 */
export const useOrganizationsControllerUpdateMe = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerUpdateMe>>,
      TError,
      { data: UpdateOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerUpdateMe>>,
  TError,
  { data: UpdateOrganizationDto },
  TContext
> => {
  return useMutation(getOrganizationsControllerUpdateMeMutationOptions(options), queryClient);
};
/**
 * @summary Get organization profile by ID (Admin/Super Admin only)
 */
export const organizationsControllerGetById = (
  id: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<OrganizationResponseDto>(
    { url: `/api/organizations/${id}`, method: "GET", signal },
    options,
  );
};

export const getOrganizationsControllerGetByIdQueryKey = (id: string) => {
  return [`/api/organizations/${id}`] as const;
};

export const getOrganizationsControllerGetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerGetById>>,
  TError = ApiErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsControllerGetByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerGetById>>> = ({
    signal,
  }) => organizationsControllerGetById(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerGetById>>
>;
export type OrganizationsControllerGetByIdQueryError = ApiErrorResponseDto;

export function useOrganizationsControllerGetById<
  TData = Awaited<ReturnType<typeof organizationsControllerGetById>>,
  TError = ApiErrorResponseDto,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerGetById<
  TData = Awaited<ReturnType<typeof organizationsControllerGetById>>,
  TError = ApiErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerGetById<
  TData = Awaited<ReturnType<typeof organizationsControllerGetById>>,
  TError = ApiErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get organization profile by ID (Admin/Super Admin only)
 */

export function useOrganizationsControllerGetById<
  TData = Awaited<ReturnType<typeof organizationsControllerGetById>>,
  TError = ApiErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOrganizationsControllerGetByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Upload an organization document (strictly PDF) and optional logo
 */
export const organizationsControllerUploadDocument = (
  createDocumentDto: CreateDocumentDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, createDocumentDto.file);
  if (createDocumentDto.logo !== undefined) {
    formData.append(`logo`, createDocumentDto.logo);
  }
  formData.append(`nameAr`, createDocumentDto.nameAr);
  if (createDocumentDto.nameEn !== undefined) {
    formData.append(`nameEn`, createDocumentDto.nameEn);
  }
  if (createDocumentDto.documentType !== undefined) {
    formData.append(`documentType`, createDocumentDto.documentType);
  }

  return api<OrgDocumentResponseDto>(
    {
      url: `/api/organizations/me/documents`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getOrganizationsControllerUploadDocumentMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerUploadDocument>>,
    TError,
    { data: CreateDocumentDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerUploadDocument>>,
  TError,
  { data: CreateDocumentDto },
  TContext
> => {
  const mutationKey = ["organizationsControllerUploadDocument"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerUploadDocument>>,
    { data: CreateDocumentDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerUploadDocument(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerUploadDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerUploadDocument>>
>;
export type OrganizationsControllerUploadDocumentMutationBody = CreateDocumentDto;
export type OrganizationsControllerUploadDocumentMutationError = ApiErrorResponseDto;

/**
 * @summary Upload an organization document (strictly PDF) and optional logo
 */
export const useOrganizationsControllerUploadDocument = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerUploadDocument>>,
      TError,
      { data: CreateDocumentDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerUploadDocument>>,
  TError,
  { data: CreateDocumentDto },
  TContext
> => {
  return useMutation(getOrganizationsControllerUploadDocumentMutationOptions(options), queryClient);
};
/**
 * @summary List organization documents
 */
export const organizationsControllerListDocuments = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<OrgDocumentResponseDto[]>(
    { url: `/api/organizations/me/documents`, method: "GET", signal },
    options,
  );
};

export const getOrganizationsControllerListDocumentsQueryKey = () => {
  return [`/api/organizations/me/documents`] as const;
};

export const getOrganizationsControllerListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListDocuments>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsControllerListDocumentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerListDocuments>>
  > = ({ signal }) => organizationsControllerListDocuments(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerListDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerListDocuments>>
>;
export type OrganizationsControllerListDocumentsQueryError = ApiErrorResponseDto;

export function useOrganizationsControllerListDocuments<
  TData = Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListDocuments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListDocuments<
  TData = Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListDocuments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListDocuments<
  TData = Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List organization documents
 */

export function useOrganizationsControllerListDocuments<
  TData = Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListDocuments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOrganizationsControllerListDocumentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete organization document
 */
export const organizationsControllerDeleteDocument = (
  id: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `/api/organizations/me/documents/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getOrganizationsControllerDeleteDocumentMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["organizationsControllerDeleteDocument"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return organizationsControllerDeleteDocument(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerDeleteDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>
>;

export type OrganizationsControllerDeleteDocumentMutationError = ApiErrorResponseDto;

/**
 * @summary Delete organization document
 */
export const useOrganizationsControllerDeleteDocument = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerDeleteDocument>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getOrganizationsControllerDeleteDocumentMutationOptions(options), queryClient);
};
/**
 * @summary Add a team member with optional CV PDF upload
 */
export const organizationsControllerAddTeamMember = (
  createTeamMemberDto: CreateTeamMemberDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (createTeamMemberDto.file !== undefined) {
    formData.append(`file`, createTeamMemberDto.file);
  }
  formData.append(`nameAr`, createTeamMemberDto.nameAr);
  if (createTeamMemberDto.nameEn !== undefined) {
    formData.append(`nameEn`, createTeamMemberDto.nameEn);
  }
  if (createTeamMemberDto.roleAr !== undefined) {
    formData.append(`roleAr`, createTeamMemberDto.roleAr);
  }
  if (createTeamMemberDto.roleEn !== undefined) {
    formData.append(`roleEn`, createTeamMemberDto.roleEn);
  }
  if (createTeamMemberDto.yearsOfExperience !== undefined) {
    formData.append(`yearsOfExperience`, createTeamMemberDto.yearsOfExperience.toString());
  }

  return api<TeamMemberResponseDto>(
    {
      url: `/api/organizations/me/team`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getOrganizationsControllerAddTeamMemberMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>,
    TError,
    { data: CreateTeamMemberDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>,
  TError,
  { data: CreateTeamMemberDto },
  TContext
> => {
  const mutationKey = ["organizationsControllerAddTeamMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>,
    { data: CreateTeamMemberDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerAddTeamMember(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerAddTeamMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>
>;
export type OrganizationsControllerAddTeamMemberMutationBody = CreateTeamMemberDto;
export type OrganizationsControllerAddTeamMemberMutationError = ApiErrorResponseDto;

/**
 * @summary Add a team member with optional CV PDF upload
 */
export const useOrganizationsControllerAddTeamMember = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>,
      TError,
      { data: CreateTeamMemberDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerAddTeamMember>>,
  TError,
  { data: CreateTeamMemberDto },
  TContext
> => {
  return useMutation(getOrganizationsControllerAddTeamMemberMutationOptions(options), queryClient);
};
/**
 * @summary List team members
 */
export const organizationsControllerListTeam = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<TeamMemberResponseDto[]>(
    { url: `/api/organizations/me/team`, method: "GET", signal },
    options,
  );
};

export const getOrganizationsControllerListTeamQueryKey = () => {
  return [`/api/organizations/me/team`] as const;
};

export const getOrganizationsControllerListTeamQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerListTeam>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListTeam>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsControllerListTeamQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerListTeam>>> = ({
    signal,
  }) => organizationsControllerListTeam(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerListTeam>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerListTeamQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerListTeam>>
>;
export type OrganizationsControllerListTeamQueryError = ApiErrorResponseDto;

export function useOrganizationsControllerListTeam<
  TData = Awaited<ReturnType<typeof organizationsControllerListTeam>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListTeam>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListTeam>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListTeam>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListTeam<
  TData = Awaited<ReturnType<typeof organizationsControllerListTeam>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListTeam>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListTeam>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListTeam>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListTeam<
  TData = Awaited<ReturnType<typeof organizationsControllerListTeam>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListTeam>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List team members
 */

export function useOrganizationsControllerListTeam<
  TData = Awaited<ReturnType<typeof organizationsControllerListTeam>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListTeam>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOrganizationsControllerListTeamQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a past project
 */
export const organizationsControllerAddProject = (
  createProjectDto: CreateProjectDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PastProjectResponseDto>(
    {
      url: `/api/organizations/me/projects`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProjectDto,
      signal,
    },
    options,
  );
};

export const getOrganizationsControllerAddProjectMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerAddProject>>,
    TError,
    { data: CreateProjectDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerAddProject>>,
  TError,
  { data: CreateProjectDto },
  TContext
> => {
  const mutationKey = ["organizationsControllerAddProject"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerAddProject>>,
    { data: CreateProjectDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerAddProject(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerAddProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerAddProject>>
>;
export type OrganizationsControllerAddProjectMutationBody = CreateProjectDto;
export type OrganizationsControllerAddProjectMutationError = ApiErrorResponseDto;

/**
 * @summary Add a past project
 */
export const useOrganizationsControllerAddProject = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerAddProject>>,
      TError,
      { data: CreateProjectDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerAddProject>>,
  TError,
  { data: CreateProjectDto },
  TContext
> => {
  return useMutation(getOrganizationsControllerAddProjectMutationOptions(options), queryClient);
};
/**
 * @summary List past projects
 */
export const organizationsControllerListProjects = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PastProjectResponseDto[]>(
    { url: `/api/organizations/me/projects`, method: "GET", signal },
    options,
  );
};

export const getOrganizationsControllerListProjectsQueryKey = () => {
  return [`/api/organizations/me/projects`] as const;
};

export const getOrganizationsControllerListProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerListProjects>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerListProjects>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsControllerListProjectsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerListProjects>>> = ({
    signal,
  }) => organizationsControllerListProjects(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerListProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerListProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerListProjects>>
>;
export type OrganizationsControllerListProjectsQueryError = ApiErrorResponseDto;

export function useOrganizationsControllerListProjects<
  TData = Awaited<ReturnType<typeof organizationsControllerListProjects>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListProjects>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListProjects>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListProjects<
  TData = Awaited<ReturnType<typeof organizationsControllerListProjects>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerListProjects>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerListProjects>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOrganizationsControllerListProjects<
  TData = Awaited<ReturnType<typeof organizationsControllerListProjects>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List past projects
 */

export function useOrganizationsControllerListProjects<
  TData = Awaited<ReturnType<typeof organizationsControllerListProjects>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerListProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOrganizationsControllerListProjectsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
