/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateServiceRequestDto,
  PaginatedRequestsResponseDto,
  RequestsControllerListAllRequestsParams,
  RequestsControllerListRequestsParams,
  ServiceRequestResponseDto,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Accepts an RFP file upload (PDF only) or a tender link. If the source type is external, either description or file is required.
 * @summary Submit a new service request
 */
export const requestsControllerCreateRequest = (
  createServiceRequestDto: CreateServiceRequestDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (createServiceRequestDto.file !== undefined) {
    formData.append(`file`, createServiceRequestDto.file);
  }
  formData.append(`rfpSourceType`, createServiceRequestDto.rfpSourceType);
  if (createServiceRequestDto.tenderId !== undefined) {
    formData.append(`tenderId`, createServiceRequestDto.tenderId);
  }
  if (createServiceRequestDto.rfpExternalDescription !== undefined) {
    formData.append(`rfpExternalDescription`, createServiceRequestDto.rfpExternalDescription);
  }

  return api<ServiceRequestResponseDto>(
    {
      url: `/api/requests`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getRequestsControllerCreateRequestMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestsControllerCreateRequest>>,
    TError,
    { data: CreateServiceRequestDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestsControllerCreateRequest>>,
  TError,
  { data: CreateServiceRequestDto },
  TContext
> => {
  const mutationKey = ["requestsControllerCreateRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestsControllerCreateRequest>>,
    { data: CreateServiceRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return requestsControllerCreateRequest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestsControllerCreateRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestsControllerCreateRequest>>
>;
export type RequestsControllerCreateRequestMutationBody = CreateServiceRequestDto;
export type RequestsControllerCreateRequestMutationError = unknown;

/**
 * @summary Submit a new service request
 */
export const useRequestsControllerCreateRequest = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestsControllerCreateRequest>>,
      TError,
      { data: CreateServiceRequestDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestsControllerCreateRequest>>,
  TError,
  { data: CreateServiceRequestDto },
  TContext
> => {
  return useMutation(getRequestsControllerCreateRequestMutationOptions(options), queryClient);
};
/**
 * Returns a paginated list of service requests for the user's organization.
 * @summary List service requests
 */
export const requestsControllerListRequests = (
  params?: RequestsControllerListRequestsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedRequestsResponseDto>(
    { url: `/api/requests`, method: "GET", params, signal },
    options,
  );
};

export const getRequestsControllerListRequestsQueryKey = (
  params?: RequestsControllerListRequestsParams,
) => {
  return [`/api/requests`, ...(params ? [params] : [])] as const;
};

export const getRequestsControllerListRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof requestsControllerListRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRequestsControllerListRequestsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof requestsControllerListRequests>>> = ({
    signal,
  }) => requestsControllerListRequests(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof requestsControllerListRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RequestsControllerListRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestsControllerListRequests>>
>;
export type RequestsControllerListRequestsQueryError = unknown;

export function useRequestsControllerListRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListRequests>>,
  TError = unknown,
>(
  params: undefined | RequestsControllerListRequestsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListRequests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerListRequests>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerListRequests>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerListRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListRequests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerListRequests>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerListRequests>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerListRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List service requests
 */

export function useRequestsControllerListRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRequestsControllerListRequestsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns a paginated list of all service requests for super admins and admins.
 * @summary List all service requests
 */
export const requestsControllerListAllRequests = (
  params?: RequestsControllerListAllRequestsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedRequestsResponseDto>(
    { url: `/api/requests/all`, method: "GET", params, signal },
    options,
  );
};

export const getRequestsControllerListAllRequestsQueryKey = (
  params?: RequestsControllerListAllRequestsParams,
) => {
  return [`/api/requests/all`, ...(params ? [params] : [])] as const;
};

export const getRequestsControllerListAllRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListAllRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListAllRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRequestsControllerListAllRequestsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof requestsControllerListAllRequests>>> = ({
    signal,
  }) => requestsControllerListAllRequests(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RequestsControllerListAllRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestsControllerListAllRequests>>
>;
export type RequestsControllerListAllRequestsQueryError = unknown;

export function useRequestsControllerListAllRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
  TError = unknown,
>(
  params: undefined | RequestsControllerListAllRequestsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListAllRequests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerListAllRequests>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerListAllRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListAllRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListAllRequests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerListAllRequests>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerListAllRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListAllRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListAllRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all service requests
 */

export function useRequestsControllerListAllRequests<
  TData = Awaited<ReturnType<typeof requestsControllerListAllRequests>>,
  TError = unknown,
>(
  params?: RequestsControllerListAllRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof requestsControllerListAllRequests>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRequestsControllerListAllRequestsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves details of a specific service request, including its current status.
 * @summary Get service request details
 */
export const requestsControllerGetRequestDetails = (
  id: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ServiceRequestResponseDto>(
    { url: `/api/requests/${id}`, method: "GET", signal },
    options,
  );
};

export const getRequestsControllerGetRequestDetailsQueryKey = (id: string) => {
  return [`/api/requests/${id}`] as const;
};

export const getRequestsControllerGetRequestDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRequestsControllerGetRequestDetailsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>> = ({
    signal,
  }) => requestsControllerGetRequestDetails(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RequestsControllerGetRequestDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>
>;
export type RequestsControllerGetRequestDetailsQueryError = unknown;

export function useRequestsControllerGetRequestDetails<
  TData = Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerGetRequestDetails<
  TData = Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestsControllerGetRequestDetails<
  TData = Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get service request details
 */

export function useRequestsControllerGetRequestDetails<
  TData = Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestsControllerGetRequestDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRequestsControllerGetRequestDetailsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Marks a service request as paid and triggers the proposal creation job.
 * @summary Simulate service request payment
 */
export const requestsControllerPayRequest = (
  id: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ServiceRequestResponseDto>(
    { url: `/api/requests/${id}/pay`, method: "POST", signal },
    options,
  );
};

export const getRequestsControllerPayRequestMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestsControllerPayRequest>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestsControllerPayRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["requestsControllerPayRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestsControllerPayRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return requestsControllerPayRequest(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestsControllerPayRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestsControllerPayRequest>>
>;

export type RequestsControllerPayRequestMutationError = unknown;

/**
 * @summary Simulate service request payment
 */
export const useRequestsControllerPayRequest = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestsControllerPayRequest>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestsControllerPayRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getRequestsControllerPayRequestMutationOptions(options), queryClient);
};
