/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AdminRequestDetailResponseDtoAdminNotes } from './adminRequestDetailResponseDtoAdminNotes';
import type { AdminRequestDetailResponseDtoDeclineReason } from './adminRequestDetailResponseDtoDeclineReason';
import type { AdminRequestDetailResponseDtoInvoiceId } from './adminRequestDetailResponseDtoInvoiceId';
import type { AdminRequestDetailResponseDtoProposalId } from './adminRequestDetailResponseDtoProposalId';
import type { AdminRequestDetailResponseDtoReviewedById } from './adminRequestDetailResponseDtoReviewedById';
import type { AdminRequestDetailResponseDtoRfpExternalDescription } from './adminRequestDetailResponseDtoRfpExternalDescription';
import type { AdminRequestDetailResponseDtoRfpFileUrl } from './adminRequestDetailResponseDtoRfpFileUrl';
import type { AdminRequestDetailResponseDtoStatus } from './adminRequestDetailResponseDtoStatus';
import type { AdminRequestDetailResponseDtoTenderId } from './adminRequestDetailResponseDtoTenderId';
import type { OrganizationResponseDto } from './organizationResponseDto';
import type { PastProjectResponseDto } from './pastProjectResponseDto';
import type { TeamMemberResponseDto } from './teamMemberResponseDto';

export interface AdminRequestDetailResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: AdminRequestDetailResponseDtoTenderId;
  /** @nullable */
  rfpFileUrl?: AdminRequestDetailResponseDtoRfpFileUrl;
  rfpSourceType: string;
  /** @nullable */
  rfpExternalDescription?: AdminRequestDetailResponseDtoRfpExternalDescription;
  status: AdminRequestDetailResponseDtoStatus;
  /** @nullable */
  adminNotes?: AdminRequestDetailResponseDtoAdminNotes;
  /** @nullable */
  declineReason?: AdminRequestDetailResponseDtoDeclineReason;
  /** @nullable */
  invoiceId?: AdminRequestDetailResponseDtoInvoiceId;
  /** @nullable */
  reviewedById?: AdminRequestDetailResponseDtoReviewedById;
  /** @nullable */
  proposalId?: AdminRequestDetailResponseDtoProposalId;
  createdAt: string;
  updatedAt: string;
  organization: OrganizationResponseDto;
  teamMembers: TeamMemberResponseDto[];
  pastProjects: PastProjectResponseDto[];
}
