/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AdminRequestsControllerListRequestsSortBy } from "./adminRequestsControllerListRequestsSortBy";
import type { AdminRequestsControllerListRequestsSortOrder } from "./adminRequestsControllerListRequestsSortOrder";
import type { AdminRequestsControllerListRequestsStatus } from "./adminRequestsControllerListRequestsStatus";

export type AdminRequestsControllerListRequestsParams = {
  /**
   * The page number to retrieve
   * @minimum 1
   */
  page?: number;
  /**
   * The number of items to retrieve per page
   * @minimum 1
   */
  limit?: number;
  /**
   * Filter requests by status
   */
  status?: AdminRequestsControllerListRequestsStatus;
  /**
   * Search query for organization name, CR number, tender title, or request ID
   */
  search?: string;
  /**
   * Field to sort requests by
   */
  sortBy?: AdminRequestsControllerListRequestsSortBy;
  /**
   * Sort order direction
   */
  sortOrder?: AdminRequestsControllerListRequestsSortOrder;
};
