/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ServiceRequestResponseDto } from "./serviceRequestResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type AdminRequestsControllerReviewRequest200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: ServiceRequestResponseDto;
};
