/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface AdminDeliverProposalDto {
  /** The URL of the final generated proposal file */
  rfpFileUrl?: string;
  /** Updated Arabic title of the proposal */
  titleAr?: string;
  /** Updated English title of the proposal */
  titleEn?: string;
}
