/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AdminProposalDetailResponseDto } from "./adminProposalDetailResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type AdminProposalsControllerDeliverProposal200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: AdminProposalDetailResponseDto;
};
