/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AdminRequestDetailResponseDtoStatus } from "./adminRequestDetailResponseDtoStatus";
import type { OrganizationResponseDto } from "./organizationResponseDto";
import type { PastProjectResponseDto } from "./pastProjectResponseDto";
import type { TeamMemberResponseDto } from "./teamMemberResponseDto";

export interface AdminRequestDetailResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: string | null;
  /** @nullable */
  rfpFileUrl?: string | null;
  mediaUrls: string[];
  rfpSourceType: string;
  /** @nullable */
  rfpExternalDescription?: string | null;
  status: AdminRequestDetailResponseDtoStatus;
  /** @nullable */
  adminNotes?: string | null;
  /** @nullable */
  declineReason?: string | null;
  /** @nullable */
  invoiceId?: string | null;
  /** @nullable */
  reviewedById?: string | null;
  /** @nullable */
  proposalId?: string | null;
  createdAt: string;
  updatedAt: string;
  organization: OrganizationResponseDto;
  teamMembers: TeamMemberResponseDto[];
  pastProjects: PastProjectResponseDto[];
}
