/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { Array } from "./array";
import type { SuccessResponseDto } from "./successResponseDto";

export type AdminProposalsControllerGetProposalSections200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: Array;
};
