/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type AdminRequestsControllerListRequestsSortBy =
  (typeof AdminRequestsControllerListRequestsSortBy)[keyof typeof AdminRequestsControllerListRequestsSortBy];

export const AdminRequestsControllerListRequestsSortBy = {
  createdAt: "createdAt",
  status: "status",
} as const;
