/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AdminProposalDetailResponseDtoStatus } from "./adminProposalDetailResponseDtoStatus";
import type { OrganizationResponseDto } from "./organizationResponseDto";
import type { OrgDocumentResponseDto } from "./orgDocumentResponseDto";
import type { PastProjectResponseDto } from "./pastProjectResponseDto";
import type { ProposalSectionResponseDto } from "./proposalSectionResponseDto";
import type { ServiceRequestResponseDto } from "./serviceRequestResponseDto";
import type { TeamMemberResponseDto } from "./teamMemberResponseDto";
import type { TenderResponseDto } from "./tenderResponseDto";

export interface AdminProposalDetailResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: string | null;
  titleAr: string;
  /** @nullable */
  titleEn?: string | null;
  status: AdminProposalDetailResponseDtoStatus;
  /** @nullable */
  rfpFileUrl?: string | null;
  language: string;
  createdById: string;
  createdAt: string;
  updatedAt: string;
  sections?: ProposalSectionResponseDto[];
  isInitialized: boolean;
  request?: ServiceRequestResponseDto;
  organization: OrganizationResponseDto;
  tender?: TenderResponseDto;
  teamMembers: TeamMemberResponseDto[];
  pastProjects: PastProjectResponseDto[];
  documents: OrgDocumentResponseDto[];
}
