/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PermissionsResponseDto } from "./permissionsResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type AuthControllerGetPermissions200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: PermissionsResponseDto;
};
