/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { RegisterResponseDto } from "./registerResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type AuthControllerForgotPassword200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: RegisterResponseDto;
};
