/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ComplianceItemResponseDtoNotes } from './complianceItemResponseDtoNotes';
import type { ComplianceItemResponseDtoRequirementEn } from './complianceItemResponseDtoRequirementEn';
import type { ComplianceItemResponseDtoStatus } from './complianceItemResponseDtoStatus';

export interface ComplianceItemResponseDto {
  id: string;
  proposalId: string;
  requirementAr: string;
  /** @nullable */
  requirementEn?: ComplianceItemResponseDtoRequirementEn;
  status: ComplianceItemResponseDtoStatus;
  /** @nullable */
  notes?: ComplianceItemResponseDtoNotes;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}
