/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ComplianceItemResponseDtoStatus } from "./complianceItemResponseDtoStatus";

export interface ComplianceItemResponseDto {
  id: string;
  proposalId: string;
  requirementAr: string;
  /** @nullable */
  requirementEn?: string | null;
  status: ComplianceItemResponseDtoStatus;
  /** @nullable */
  notes?: string | null;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}
