/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ComplianceItemResponseDtoStatus = typeof ComplianceItemResponseDtoStatus[keyof typeof ComplianceItemResponseDtoStatus];


export const ComplianceItemResponseDtoStatus = {
  pending: 'pending',
  compliant: 'compliant',
  non_compliant: 'non_compliant',
  not_applicable: 'not_applicable',
} as const;
