/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Optional custom metadata fields for the organization
 */
export type CreateOrganizationDtoMetadata = { [key: string]: unknown };
