/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface CreateDocumentDto {
  /** The PDF document file to upload */
  file: Blob;
  /** Optional organization logo image file (JPEG/PNG/WebP/GIF) */
  logo?: Blob;
  /**
   * The Arabic name of the document
   * @maxLength 255
   */
  nameAr: string;
  /**
   * The English name of the document
   * @maxLength 255
   */
  nameEn?: string;
  /**
   * The type or category of the document (e.g. CR, VAT, LocalContent)
   * @maxLength 50
   */
  documentType?: string;
}
