/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface CreateTeamMemberDto {
  /** The PDF CV file to upload for the team member */
  file?: Blob;
  /**
     * The Arabic name of the team member
     * @maxLength 255
     */
  nameAr: string;
  /**
     * The English name of the team member
     * @maxLength 255
     */
  nameEn?: string;
  /**
     * The Arabic role/title of the team member
     * @maxLength 255
     */
  roleAr?: string;
  /**
     * The English role/title of the team member
     * @maxLength 255
     */
  roleEn?: string;
  /**
     * Years of experience of the team member
     * @minimum 0
     */
  yearsOfExperience?: number;
}
