/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoMetadata } from "./createPaymentDtoMetadata";

export interface CreatePaymentDto {
  /** Amount in the smallest currency unit (e.g., 1000 = $10.00 USD). */
  amountInCents: number;
  /** ISO 4217 currency code. Defaults to the server-configured currency if omitted. */
  currency?: string;
  /** Optional metadata (e.g., reference ID). */
  metadata?: CreatePaymentDtoMetadata;
}
