/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { CreateServiceRequestDtoRfpSourceType } from "./createServiceRequestDtoRfpSourceType";

export interface CreateServiceRequestDto {
  /** The RFP PDF document file to upload */
  file?: Blob;
  /** Additional media/documents to upload */
  files?: Blob[];
  /** Source type of RFP */
  rfpSourceType: CreateServiceRequestDtoRfpSourceType;
  /** The ID of the tender, if from platform */
  tenderId?: string;
  /** Description of the request, if external */
  rfpExternalDescription?: string;
}
