/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Optional metadata (e.g., reference ID).
 */
export type CreatePaymentDtoMetadata = { [key: string]: unknown };
