/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectDto {
  /**
     * The Arabic title of the project
     * @maxLength 500
     */
  titleAr: string;
  /**
     * The English title of the project
     * @maxLength 500
     */
  titleEn?: string;
  /**
     * The Arabic name of the client
     * @maxLength 255
     */
  clientNameAr?: string;
  /**
     * The English name of the client
     * @maxLength 255
     */
  clientNameEn?: string;
  /** The monetary value of the project */
  value?: string;
  /** The start date of the project */
  startDate?: string;
  /** The end date of the project */
  endDate?: string;
  /** The Arabic description of the project */
  descriptionAr?: string;
  /** The English description of the project */
  descriptionEn?: string;
}
