/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Source type of RFP
 */
export type CreateServiceRequestDtoRfpSourceType =
  (typeof CreateServiceRequestDtoRfpSourceType)[keyof typeof CreateServiceRequestDtoRfpSourceType];

export const CreateServiceRequestDtoRfpSourceType = {
  platform: "platform",
  external: "external",
} as const;
