/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { CreateOrganizationDtoMetadata } from './createOrganizationDtoMetadata';

export interface CreateOrganizationDto {
  /**
     * The Arabic name of the organization
     * @maxLength 255
     */
  nameAr: string;
  /**
     * The English name of the organization
     * @maxLength 255
     */
  nameEn?: string;
  /**
     * Commercial Registration (CR) number of the organization
     * @maxLength 50
     */
  crNumber?: string;
  /** Expiration date of the Commercial Registration */
  crExpiry?: string;
  /** Local content score of the organization */
  localContentScore?: string;
  /**
     * Industry sector of the organization
     * @maxLength 100
     */
  sector?: string;
  /**
     * Size of the organization
     * @maxLength 50
     */
  size?: string;
  /** Optional custom metadata fields for the organization */
  metadata?: CreateOrganizationDtoMetadata;
}
