/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Contractors classifications list
 */
export type CreateTenderWithRfpDtoClassifications = { [key: string]: unknown };
