/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ExportControllerExportTestPdfLocale = typeof ExportControllerExportTestPdfLocale[keyof typeof ExportControllerExportTestPdfLocale];


export const ExportControllerExportTestPdfLocale = {
  ar: 'ar',
  en: 'en',
} as const;
