/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ExportControllerExportTestWordLocale = typeof ExportControllerExportTestWordLocale[keyof typeof ExportControllerExportTestWordLocale];


export const ExportControllerExportTestWordLocale = {
  ar: 'ar',
  en: 'en',
} as const;
