/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ExportControllerExportPdfLocale } from "./exportControllerExportPdfLocale";

export type ExportControllerExportPdfParams = {
  /**
   * The locale for the exported document (defaults to ar)
   */
  locale?: ExportControllerExportPdfLocale;
};
