/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ExportControllerExportWordLocale = typeof ExportControllerExportWordLocale[keyof typeof ExportControllerExportWordLocale];


export const ExportControllerExportWordLocale = {
  ar: 'ar',
  en: 'en',
} as const;
