/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ExportControllerExportTestPdfLocale } from './exportControllerExportTestPdfLocale';

export type ExportControllerExportTestPdfParams = {
/**
 * The locale for the exported document (defaults to ar)
 */
locale?: ExportControllerExportTestPdfLocale;
};
