/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ExportControllerExportWordLocale } from './exportControllerExportWordLocale';

export type ExportControllerExportWordParams = {
/**
 * The locale for the exported document (defaults to ar)
 */
locale?: ExportControllerExportWordLocale;
};
