/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ExportControllerExportPdfLocale =
  (typeof ExportControllerExportPdfLocale)[keyof typeof ExportControllerExportPdfLocale];

export const ExportControllerExportPdfLocale = {
  ar: "ar",
  en: "en",
} as const;
