/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ExportControllerExportTestWordLocale } from './exportControllerExportTestWordLocale';

export type ExportControllerExportTestWordParams = {
/**
 * The locale for the exported document (defaults to ar)
 */
locale?: ExportControllerExportTestWordLocale;
};
