/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface FileResponseDto {
  /** Full storage path of the file */
  path: string;
  /** File size in bytes */
  size: number;
  /** File MIME type */
  mimetype: string;
  /**
   * Entity tag of the stored resource
   * @nullable
   */
  etag?: string | null;
  /**
   * Last modification date of the resource
   * @nullable
   */
  lastModified?: string | null;
  /** Public URL to access the file */
  url: string;
  /**
   * Public URL to access the thumbnail (if generated)
   * @nullable
   */
  thumbnailUrl?: string | null;
}
