/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * The preferred language for the reset email
 */
export type ForgotPasswordDtoLocale =
  (typeof ForgotPasswordDtoLocale)[keyof typeof ForgotPasswordDtoLocale];

export const ForgotPasswordDtoLocale = {
  en: "en",
  ar: "ar",
} as const;
