/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ForgotPasswordDtoLocale } from "./forgotPasswordDtoLocale";

export interface ForgotPasswordDto {
  /** The email address of the user who forgot their password */
  email: string;
  /** The preferred language for the reset email */
  locale?: ForgotPasswordDtoLocale;
}
