/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;
