/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { RequestMagicLinkResponseDto } from './requestMagicLinkResponseDto';
import type { SuccessResponseDto } from './successResponseDto';

export type MagicLinkControllerRequest200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: RequestMagicLinkResponseDto;
};
