/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Target folder
 */
export type MediaControllerUploadSingleBodyFolder = typeof MediaControllerUploadSingleBodyFolder[keyof typeof MediaControllerUploadSingleBodyFolder];


export const MediaControllerUploadSingleBodyFolder = {
  users: 'users',
  general: 'general',
  temp: 'temp',
} as const;
