/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * File visibility
 */
export type MediaControllerUploadSingleBodyVisibility =
  (typeof MediaControllerUploadSingleBodyVisibility)[keyof typeof MediaControllerUploadSingleBodyVisibility];

export const MediaControllerUploadSingleBodyVisibility = {
  public: "public",
  private: "private",
} as const;
