/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * File visibility
 */
export type MediaControllerUploadMultipleBodyVisibility =
  (typeof MediaControllerUploadMultipleBodyVisibility)[keyof typeof MediaControllerUploadMultipleBodyVisibility];

export const MediaControllerUploadMultipleBodyVisibility = {
  public: "public",
  private: "private",
} as const;
