/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { MediaControllerUploadSingleBodyFolder } from './mediaControllerUploadSingleBodyFolder';
import type { MediaControllerUploadSingleBodyVisibility } from './mediaControllerUploadSingleBodyVisibility';

export type MediaControllerUploadSingleBody = {
  file: Blob;
  /** Target folder */
  folder?: MediaControllerUploadSingleBodyFolder;
  /** File visibility */
  visibility?: MediaControllerUploadSingleBodyVisibility;
};
