/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { MediaControllerUploadMultipleBodyFolder } from './mediaControllerUploadMultipleBodyFolder';
import type { MediaControllerUploadMultipleBodyVisibility } from './mediaControllerUploadMultipleBodyVisibility';

export type MediaControllerUploadMultipleBody = {
  files: Blob[];
  /** Target folder */
  folder?: MediaControllerUploadMultipleBodyFolder;
  /** File visibility */
  visibility?: MediaControllerUploadMultipleBodyVisibility;
};
