/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface OnboardingDto {
  /** The core details of the organization to register (stringified JSON) */
  organization: string;
  /** List of team members to add during onboarding (stringified JSON) */
  teamMembers?: string;
  /** List of past projects to add during onboarding (stringified JSON) */
  projects?: string;
  /** List of documents to upload during onboarding (stringified JSON) */
  documents?: string;
}
