/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationResponseDto } from "./organizationResponseDto";
import type { OrgDocumentResponseDto } from "./orgDocumentResponseDto";
import type { PastProjectResponseDto } from "./pastProjectResponseDto";
import type { TeamMemberResponseDto } from "./teamMemberResponseDto";

export interface OnboardingResponseDto {
  /** The registered organization details */
  organization: OrganizationResponseDto;
  /** List of team members created */
  teamMembers: TeamMemberResponseDto[];
  /** List of past projects created */
  projects: PastProjectResponseDto[];
  /** List of uploaded documents */
  documents: OrgDocumentResponseDto[];
}
