/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationResponseDtoMetadata } from "./organizationResponseDtoMetadata";

export interface OrganizationResponseDto {
  id: string;
  nameAr: string;
  /** @nullable */
  nameEn?: string | null;
  /** @nullable */
  crNumber?: string | null;
  /** @nullable */
  crExpiry?: string | null;
  /** @nullable */
  localContentScore?: string | null;
  /** @nullable */
  sector?: string | null;
  /** @nullable */
  size?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  /** @nullable */
  metadata?: OrganizationResponseDtoMetadata;
  createdAt: string;
  updatedAt: string;
}
