/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationResponseDtoCrExpiry } from './organizationResponseDtoCrExpiry';
import type { OrganizationResponseDtoCrNumber } from './organizationResponseDtoCrNumber';
import type { OrganizationResponseDtoLocalContentScore } from './organizationResponseDtoLocalContentScore';
import type { OrganizationResponseDtoLogoUrl } from './organizationResponseDtoLogoUrl';
import type { OrganizationResponseDtoMetadata } from './organizationResponseDtoMetadata';
import type { OrganizationResponseDtoNameEn } from './organizationResponseDtoNameEn';
import type { OrganizationResponseDtoSector } from './organizationResponseDtoSector';
import type { OrganizationResponseDtoSize } from './organizationResponseDtoSize';

export interface OrganizationResponseDto {
  id: string;
  nameAr: string;
  /** @nullable */
  nameEn?: OrganizationResponseDtoNameEn;
  /** @nullable */
  crNumber?: OrganizationResponseDtoCrNumber;
  /** @nullable */
  crExpiry?: OrganizationResponseDtoCrExpiry;
  /** @nullable */
  localContentScore?: OrganizationResponseDtoLocalContentScore;
  /** @nullable */
  sector?: OrganizationResponseDtoSector;
  /** @nullable */
  size?: OrganizationResponseDtoSize;
  /** @nullable */
  logoUrl?: OrganizationResponseDtoLogoUrl;
  /** @nullable */
  metadata?: OrganizationResponseDtoMetadata;
  createdAt: string;
  updatedAt: string;
}
