/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { OrgDocumentResponseDtoDocumentType } from './orgDocumentResponseDtoDocumentType';
import type { OrgDocumentResponseDtoNameEn } from './orgDocumentResponseDtoNameEn';

export interface OrgDocumentResponseDto {
  id: string;
  organizationId: string;
  nameAr: string;
  /** @nullable */
  nameEn?: OrgDocumentResponseDtoNameEn;
  fileUrl: string;
  /** @nullable */
  documentType?: OrgDocumentResponseDtoDocumentType;
  createdAt: string;
  updatedAt: string;
}
