/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface OrgDocumentResponseDto {
  id: string;
  organizationId: string;
  nameAr: string;
  /** @nullable */
  nameEn?: string | null;
  fileUrl: string;
  /** @nullable */
  documentType?: string | null;
  createdAt: string;
  updatedAt: string;
}
