/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaginationMetaDto } from "./paginationMetaDto";
import type { ProposalResponseDto } from "./proposalResponseDto";

export interface PaginatedProposalsResponseDto {
  /** The list of proposals */
  data: ProposalResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}
