/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface PaginationMetaDto {
  /** Total number of items matching the query */
  total: number;
  /** Current page number */
  page: number;
  /** Limit of items returned per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
}
