/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaginationMetaDto } from "./paginationMetaDto";
import type { ServiceRequestResponseDto } from "./serviceRequestResponseDto";

export interface PaginatedRequestsResponseDto {
  /** The list of service requests */
  data: ServiceRequestResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}
