/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaginatedTendersResponseDtoMeta } from "./paginatedTendersResponseDtoMeta";
import type { TenderResponseDto } from "./tenderResponseDto";

export interface PaginatedTendersResponseDto {
  data: TenderResponseDto[];
  meta: PaginatedTendersResponseDtoMeta;
}
