/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PastProjectResponseDtoClientNameAr } from './pastProjectResponseDtoClientNameAr';
import type { PastProjectResponseDtoClientNameEn } from './pastProjectResponseDtoClientNameEn';
import type { PastProjectResponseDtoDescriptionAr } from './pastProjectResponseDtoDescriptionAr';
import type { PastProjectResponseDtoDescriptionEn } from './pastProjectResponseDtoDescriptionEn';
import type { PastProjectResponseDtoEndDate } from './pastProjectResponseDtoEndDate';
import type { PastProjectResponseDtoStartDate } from './pastProjectResponseDtoStartDate';
import type { PastProjectResponseDtoTitleEn } from './pastProjectResponseDtoTitleEn';
import type { PastProjectResponseDtoValue } from './pastProjectResponseDtoValue';

export interface PastProjectResponseDto {
  id: string;
  organizationId: string;
  titleAr: string;
  /** @nullable */
  titleEn?: PastProjectResponseDtoTitleEn;
  /** @nullable */
  clientNameAr?: PastProjectResponseDtoClientNameAr;
  /** @nullable */
  clientNameEn?: PastProjectResponseDtoClientNameEn;
  /** @nullable */
  value?: PastProjectResponseDtoValue;
  /** @nullable */
  startDate?: PastProjectResponseDtoStartDate;
  /** @nullable */
  endDate?: PastProjectResponseDtoEndDate;
  /** @nullable */
  descriptionAr?: PastProjectResponseDtoDescriptionAr;
  /** @nullable */
  descriptionEn?: PastProjectResponseDtoDescriptionEn;
  createdAt: string;
  updatedAt: string;
}
