/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type PastProjectResponseDtoDescriptionAr = { [key: string]: unknown } | null;
