/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface PastProjectResponseDto {
  id: string;
  organizationId: string;
  titleAr: string;
  /** @nullable */
  titleEn?: string | null;
  /** @nullable */
  clientNameAr?: string | null;
  /** @nullable */
  clientNameEn?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  descriptionAr?: string | null;
  /** @nullable */
  descriptionEn?: string | null;
  createdAt: string;
  updatedAt: string;
}
