/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the payment
 */
export type PaymentStatusResultDtoStatus = typeof PaymentStatusResultDtoStatus[keyof typeof PaymentStatusResultDtoStatus];


export const PaymentStatusResultDtoStatus = {
  pending: 'pending',
  processing: 'processing',
  succeeded: 'succeeded',
  failed: 'failed',
  cancelled: 'cancelled',
  refunded: 'refunded',
  skipped: 'skipped',
  processed: 'processed',
} as const;
