/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaymentStatusResultDtoStatus } from './paymentStatusResultDtoStatus';

export interface PaymentStatusResultDto {
  /** The provider-assigned transaction/payment intent ID */
  providerTransactionId: string;
  /** Current status of the payment */
  status: PaymentStatusResultDtoStatus;
  /** Amount in the smallest currency unit */
  amountInCents: number;
  /** ISO 4217 currency code */
  currency: string;
}
