/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaymentResultDtoStatus } from './paymentResultDtoStatus';

export interface PaymentResultDto {
  /** The provider-assigned transaction/payment intent ID */
  providerTransactionId: string;
  /** Redirect URL for hosted payment pages (if applicable) */
  redirectUrl?: string;
  /** Current status of the payment */
  status: PaymentResultDtoStatus;
}
