/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProvidersResponseDto } from "./providersResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type PaymentsControllerListProviders200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: ProvidersResponseDto;
};
