/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PaymentStatusResultDto } from "./paymentStatusResultDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type PaymentsControllerGetPaymentStatus200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: PaymentStatusResultDto;
};
