/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProposalResponseDtoStatus } from "./proposalResponseDtoStatus";
import type { ProposalSectionResponseDto } from "./proposalSectionResponseDto";

export interface ProposalResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: string | null;
  titleAr: string;
  /** @nullable */
  titleEn?: string | null;
  status: ProposalResponseDtoStatus;
  /** @nullable */
  rfpFileUrl?: string | null;
  language: string;
  createdById: string;
  createdAt: string;
  updatedAt: string;
  sections?: ProposalSectionResponseDto[];
}
