/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProposalSectionResponseDtoContentAr } from "./proposalSectionResponseDtoContentAr";
import type { ProposalSectionResponseDtoContentEn } from "./proposalSectionResponseDtoContentEn";
import type { ProposalSectionResponseDtoStatus } from "./proposalSectionResponseDtoStatus";
import type { ProposalSectionResponseDtoTitleEn } from "./proposalSectionResponseDtoTitleEn";

export interface ProposalSectionResponseDto {
  id: string;
  proposalId: string;
  sectionType: string;
  titleAr: string;
  /** @nullable */
  titleEn?: ProposalSectionResponseDtoTitleEn;
  /** @nullable */
  contentAr?: ProposalSectionResponseDtoContentAr;
  /** @nullable */
  contentEn?: ProposalSectionResponseDtoContentEn;
  aiGenerated: boolean;
  humanApproved: boolean;
  sortOrder: number;
  status: ProposalSectionResponseDtoStatus;
  createdAt: string;
  updatedAt: string;
}
