/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProposalSectionResponseDtoStatus } from "./proposalSectionResponseDtoStatus";

export interface ProposalSectionResponseDto {
  id: string;
  proposalId: string;
  sectionType: string;
  titleAr: string;
  /** @nullable */
  titleEn?: string | null;
  /** @nullable */
  contentAr?: string | null;
  /** @nullable */
  contentEn?: string | null;
  aiGenerated: boolean;
  humanApproved: boolean;
  sortOrder: number;
  status: ProposalSectionResponseDtoStatus;
  createdAt: string;
  updatedAt: string;
}
