/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProposalResponseDtoRfpFileUrl } from './proposalResponseDtoRfpFileUrl';
import type { ProposalResponseDtoStatus } from './proposalResponseDtoStatus';
import type { ProposalResponseDtoTenderId } from './proposalResponseDtoTenderId';
import type { ProposalResponseDtoTitleEn } from './proposalResponseDtoTitleEn';
import type { ProposalSectionResponseDto } from './proposalSectionResponseDto';

export interface ProposalResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: ProposalResponseDtoTenderId;
  titleAr: string;
  /** @nullable */
  titleEn?: ProposalResponseDtoTitleEn;
  status: ProposalResponseDtoStatus;
  /** @nullable */
  rfpFileUrl?: ProposalResponseDtoRfpFileUrl;
  language: string;
  createdById: string;
  createdAt: string;
  updatedAt: string;
  sections?: ProposalSectionResponseDto[];
}
