/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type ProvidersResponseDtoProvidersItem = typeof ProvidersResponseDtoProvidersItem[keyof typeof ProvidersResponseDtoProvidersItem];


export const ProvidersResponseDtoProvidersItem = {
  stripe: 'stripe',
  paymob: 'paymob',
  mock: 'mock',
} as const;
