/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ProvidersResponseDtoProvidersItem } from "./providersResponseDtoProvidersItem";

export interface ProvidersResponseDto {
  /** List of registered payment provider names */
  providers: ProvidersResponseDtoProvidersItem[];
}
