/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type PythonAiControllerGenerateLocale =
  (typeof PythonAiControllerGenerateLocale)[keyof typeof PythonAiControllerGenerateLocale];

export const PythonAiControllerGenerateLocale = {
  en: "en",
  ar: "ar",
} as const;
