/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { PythonAiControllerGenerateLocale } from "./pythonAiControllerGenerateLocale";

export type PythonAiControllerGenerateParams = {
  /**
   * Locale
   */
  locale?: PythonAiControllerGenerateLocale;
};
