/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { RefundResultDtoStatus } from './refundResultDtoStatus';

export interface RefundResultDto {
  /** The provider-assigned refund ID */
  providerRefundId: string;
  /** Status of the refund */
  status: RefundResultDtoStatus;
  /** Amount refunded in the smallest currency unit */
  amountInCents: number;
}
