/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface RefundPaymentDto {
  /** The provider's transaction ID to refund */
  providerTransactionId: string;
  /** Optional partial refund amount in cents. If omitted, a full refund is issued. */
  amountInCents?: number;
}
