/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the refund
 */
export type RefundResultDtoStatus =
  (typeof RefundResultDtoStatus)[keyof typeof RefundResultDtoStatus];

export const RefundResultDtoStatus = {
  succeeded: "succeeded",
  pending: "pending",
  failed: "failed",
} as const;
