/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface RegisterResponseDto {
  /** The verification token (only returned when EXPOSE_TESTING_TOKENS is enabled) */
  token?: string;
}
