/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type RequestsControllerListRequestsParams = {
  /**
   * The page number to retrieve
   * @minimum 1
   */
  page?: number;
  /**
   * The number of items to retrieve per page
   * @minimum 1
   */
  limit?: number;
};
