/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** The raw password reset token received in the email */
  token: string;
  /**
   * The new password for the user (8-32 characters)
   * @minLength 8
   * @maxLength 32
   */
  password: string;
}
