/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Decision to accept or decline the request
 */
export type ReviewRequestDtoDecision = typeof ReviewRequestDtoDecision[keyof typeof ReviewRequestDtoDecision];


export const ReviewRequestDtoDecision = {
  accept: 'accept',
  decline: 'decline',
} as const;
