/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ServiceRequestResponseDtoStatus } from "./serviceRequestResponseDtoStatus";

export interface ServiceRequestResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: string | null;
  /** @nullable */
  rfpFileUrl?: string | null;
  mediaUrls: string[];
  rfpSourceType: string;
  /** @nullable */
  rfpExternalDescription?: string | null;
  status: ServiceRequestResponseDtoStatus;
  /** @nullable */
  adminNotes?: string | null;
  /** @nullable */
  declineReason?: string | null;
  /** @nullable */
  invoiceId?: string | null;
  /** @nullable */
  reviewedById?: string | null;
  /** @nullable */
  proposalId?: string | null;
  createdAt: string;
  updatedAt: string;
}
