/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ServiceRequestResponseDtoAdminNotes } from './serviceRequestResponseDtoAdminNotes';
import type { ServiceRequestResponseDtoDeclineReason } from './serviceRequestResponseDtoDeclineReason';
import type { ServiceRequestResponseDtoInvoiceId } from './serviceRequestResponseDtoInvoiceId';
import type { ServiceRequestResponseDtoProposalId } from './serviceRequestResponseDtoProposalId';
import type { ServiceRequestResponseDtoReviewedById } from './serviceRequestResponseDtoReviewedById';
import type { ServiceRequestResponseDtoRfpExternalDescription } from './serviceRequestResponseDtoRfpExternalDescription';
import type { ServiceRequestResponseDtoRfpFileUrl } from './serviceRequestResponseDtoRfpFileUrl';
import type { ServiceRequestResponseDtoStatus } from './serviceRequestResponseDtoStatus';
import type { ServiceRequestResponseDtoTenderId } from './serviceRequestResponseDtoTenderId';

export interface ServiceRequestResponseDto {
  id: string;
  organizationId: string;
  /** @nullable */
  tenderId?: ServiceRequestResponseDtoTenderId;
  /** @nullable */
  rfpFileUrl?: ServiceRequestResponseDtoRfpFileUrl;
  rfpSourceType: string;
  /** @nullable */
  rfpExternalDescription?: ServiceRequestResponseDtoRfpExternalDescription;
  status: ServiceRequestResponseDtoStatus;
  /** @nullable */
  adminNotes?: ServiceRequestResponseDtoAdminNotes;
  /** @nullable */
  declineReason?: ServiceRequestResponseDtoDeclineReason;
  /** @nullable */
  invoiceId?: ServiceRequestResponseDtoInvoiceId;
  /** @nullable */
  reviewedById?: ServiceRequestResponseDtoReviewedById;
  /** @nullable */
  proposalId?: ServiceRequestResponseDtoProposalId;
  createdAt: string;
  updatedAt: string;
}
