/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { TeamMemberResponseDtoCvFileUrl } from './teamMemberResponseDtoCvFileUrl';
import type { TeamMemberResponseDtoNameEn } from './teamMemberResponseDtoNameEn';
import type { TeamMemberResponseDtoRoleAr } from './teamMemberResponseDtoRoleAr';
import type { TeamMemberResponseDtoRoleEn } from './teamMemberResponseDtoRoleEn';
import type { TeamMemberResponseDtoYearsOfExperience } from './teamMemberResponseDtoYearsOfExperience';

export interface TeamMemberResponseDto {
  id: string;
  organizationId: string;
  nameAr: string;
  /** @nullable */
  nameEn?: TeamMemberResponseDtoNameEn;
  /** @nullable */
  roleAr?: TeamMemberResponseDtoRoleAr;
  /** @nullable */
  roleEn?: TeamMemberResponseDtoRoleEn;
  /** @nullable */
  cvFileUrl?: TeamMemberResponseDtoCvFileUrl;
  /** @nullable */
  yearsOfExperience?: TeamMemberResponseDtoYearsOfExperience;
  createdAt: string;
  updatedAt: string;
}
