/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface TeamMemberResponseDto {
  id: string;
  organizationId: string;
  nameAr: string;
  /** @nullable */
  nameEn?: string | null;
  /** @nullable */
  roleAr?: string | null;
  /** @nullable */
  roleEn?: string | null;
  /** @nullable */
  cvFileUrl?: string | null;
  /** @nullable */
  yearsOfExperience?: number | null;
  createdAt: string;
  updatedAt: string;
}
