/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { TenderCategoryResponseDto } from "./tenderCategoryResponseDto";
import type { TenderResponseDtoAwardResults } from "./tenderResponseDtoAwardResults";
import type { TenderResponseDtoClassifications } from "./tenderResponseDtoClassifications";
import type { TenderResponseDtoLocalContentMechanisms } from "./tenderResponseDtoLocalContentMechanisms";
import type { TenderResponseDtoMetadata } from "./tenderResponseDtoMetadata";
import type { TenderResponseDtoStatus } from "./tenderResponseDtoStatus";

export interface TenderResponseDto {
  id: string;
  /** @nullable */
  externalId?: string | null;
  titleAr: string;
  /** @nullable */
  titleEn?: string | null;
  /** @nullable */
  descriptionAr?: string | null;
  /** @nullable */
  descriptionEn?: string | null;
  /** @nullable */
  entityNameAr?: string | null;
  /** @nullable */
  entityNameEn?: string | null;
  /** @nullable */
  sector?: string | null;
  /** @nullable */
  region?: string | null;
  /** @nullable */
  tenderType?: string | null;
  status: TenderResponseDtoStatus;
  /** @nullable */
  estimatedBudget?: number | null;
  /** @nullable */
  documentPrice?: number | null;
  /** @nullable */
  submissionDeadline?: string | null;
  /** @nullable */
  publishDate?: string | null;
  /** @nullable */
  awardDate?: string | null;
  /** @nullable */
  contractDurationMonths?: number | null;
  /** @nullable */
  bidCount?: number | null;
  source: string;
  /** RFP (كراسة شروط) PDF file URL */
  rfpFileUrl: string;
  targetSme: boolean;
  localContentRequired: boolean;
  /** @nullable */
  metadata?: TenderResponseDtoMetadata;
  /** @nullable */
  tenderNumber?: string | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  tenderPurposeAr?: string | null;
  /** @nullable */
  tenderPurposeEn?: string | null;
  /** @nullable */
  contractDurationAr?: string | null;
  /** @nullable */
  contractDurationEn?: string | null;
  insuranceRequired?: boolean;
  /** @nullable */
  governmentEntityAr?: string | null;
  /** @nullable */
  governmentEntityEn?: string | null;
  /** @nullable */
  competentAuthorityAr?: string | null;
  /** @nullable */
  competentAuthorityEn?: string | null;
  /** @nullable */
  remainingTimeAr?: string | null;
  /** @nullable */
  remainingTimeEn?: string | null;
  /** @nullable */
  submissionMethodAr?: string | null;
  /** @nullable */
  submissionMethodEn?: string | null;
  initialGuaranteeRequired?: boolean;
  /** @nullable */
  initialGuaranteeAddressAr?: string | null;
  /** @nullable */
  initialGuaranteeAddressEn?: string | null;
  finalGuarantee?: number;
  /** @nullable */
  inquiriesDeadline?: string | null;
  /** @nullable */
  bidsOpeningDate?: string | null;
  /** @nullable */
  bidsEvaluationDate?: string | null;
  suspensionPeriod?: number;
  /** @nullable */
  expectedAwardDate?: string | null;
  /** @nullable */
  workStartDate?: string | null;
  /** @nullable */
  inquiriesStartDate?: string | null;
  maxInquiriesResponseDuration?: number;
  /** @nullable */
  bidsOpeningLocationAr?: string | null;
  /** @nullable */
  bidsOpeningLocationEn?: string | null;
  classifications?: TenderResponseDtoClassifications;
  /** @nullable */
  executionLocationAr?: string | null;
  /** @nullable */
  executionLocationEn?: string | null;
  /** @nullable */
  detailsAr?: string | null;
  /** @nullable */
  detailsEn?: string | null;
  /** @nullable */
  tenderActivityAr?: string | null;
  /** @nullable */
  tenderActivityEn?: string | null;
  includesSupplyItems?: boolean;
  includesConstructionWorks?: boolean;
  includesMaintenanceAndOperationWorks?: boolean;
  awardResults?: TenderResponseDtoAwardResults;
  localContentMechanisms?: TenderResponseDtoLocalContentMechanisms;
  localContentTermsPdfUrl?: string;
  categories: TenderCategoryResponseDto[];
  createdAt: string;
  updatedAt: string;
}
