/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type TendersControllerListTendersSortBy =
  (typeof TendersControllerListTendersSortBy)[keyof typeof TendersControllerListTendersSortBy];

export const TendersControllerListTendersSortBy = {
  "publishDate:desc": "publishDate:desc",
  "publishDate:asc": "publishDate:asc",
  publishDate_desc: "publishDate_desc",
  publishDate_asc: "publishDate_asc",
  publishDate: "publishDate",
  "submissionDeadline:desc": "submissionDeadline:desc",
  "submissionDeadline:asc": "submissionDeadline:asc",
  submissionDeadline_desc: "submissionDeadline_desc",
  submissionDeadline_asc: "submissionDeadline_asc",
  submissionDeadline: "submissionDeadline",
  "estimatedBudget:desc": "estimatedBudget:desc",
  "estimatedBudget:asc": "estimatedBudget:asc",
  estimatedBudget_desc: "estimatedBudget_desc",
  estimatedBudget_asc: "estimatedBudget_asc",
  estimatedBudget: "estimatedBudget",
  "createdAt:desc": "createdAt:desc",
  "createdAt:asc": "createdAt:asc",
  createdAt_desc: "createdAt_desc",
  createdAt_asc: "createdAt_asc",
  createdAt: "createdAt",
} as const;
