/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { TenderCategoryResponseDto } from './tenderCategoryResponseDto';
import type { TenderResponseDtoAwardDate } from './tenderResponseDtoAwardDate';
import type { TenderResponseDtoAwardResults } from './tenderResponseDtoAwardResults';
import type { TenderResponseDtoBidCount } from './tenderResponseDtoBidCount';
import type { TenderResponseDtoBidsEvaluationDate } from './tenderResponseDtoBidsEvaluationDate';
import type { TenderResponseDtoBidsOpeningDate } from './tenderResponseDtoBidsOpeningDate';
import type { TenderResponseDtoBidsOpeningLocationAr } from './tenderResponseDtoBidsOpeningLocationAr';
import type { TenderResponseDtoBidsOpeningLocationEn } from './tenderResponseDtoBidsOpeningLocationEn';
import type { TenderResponseDtoClassifications } from './tenderResponseDtoClassifications';
import type { TenderResponseDtoCompetentAuthorityAr } from './tenderResponseDtoCompetentAuthorityAr';
import type { TenderResponseDtoCompetentAuthorityEn } from './tenderResponseDtoCompetentAuthorityEn';
import type { TenderResponseDtoContractDurationAr } from './tenderResponseDtoContractDurationAr';
import type { TenderResponseDtoContractDurationEn } from './tenderResponseDtoContractDurationEn';
import type { TenderResponseDtoContractDurationMonths } from './tenderResponseDtoContractDurationMonths';
import type { TenderResponseDtoDescriptionAr } from './tenderResponseDtoDescriptionAr';
import type { TenderResponseDtoDescriptionEn } from './tenderResponseDtoDescriptionEn';
import type { TenderResponseDtoDetailsAr } from './tenderResponseDtoDetailsAr';
import type { TenderResponseDtoDetailsEn } from './tenderResponseDtoDetailsEn';
import type { TenderResponseDtoDocumentPrice } from './tenderResponseDtoDocumentPrice';
import type { TenderResponseDtoEntityNameAr } from './tenderResponseDtoEntityNameAr';
import type { TenderResponseDtoEntityNameEn } from './tenderResponseDtoEntityNameEn';
import type { TenderResponseDtoEstimatedBudget } from './tenderResponseDtoEstimatedBudget';
import type { TenderResponseDtoExecutionLocationAr } from './tenderResponseDtoExecutionLocationAr';
import type { TenderResponseDtoExecutionLocationEn } from './tenderResponseDtoExecutionLocationEn';
import type { TenderResponseDtoExpectedAwardDate } from './tenderResponseDtoExpectedAwardDate';
import type { TenderResponseDtoExternalId } from './tenderResponseDtoExternalId';
import type { TenderResponseDtoFinalGuarantee } from './tenderResponseDtoFinalGuarantee';
import type { TenderResponseDtoGovernmentEntityAr } from './tenderResponseDtoGovernmentEntityAr';
import type { TenderResponseDtoGovernmentEntityEn } from './tenderResponseDtoGovernmentEntityEn';
import type { TenderResponseDtoInitialGuaranteeAddressAr } from './tenderResponseDtoInitialGuaranteeAddressAr';
import type { TenderResponseDtoInitialGuaranteeAddressEn } from './tenderResponseDtoInitialGuaranteeAddressEn';
import type { TenderResponseDtoInquiriesDeadline } from './tenderResponseDtoInquiriesDeadline';
import type { TenderResponseDtoInquiriesStartDate } from './tenderResponseDtoInquiriesStartDate';
import type { TenderResponseDtoLocalContentMechanisms } from './tenderResponseDtoLocalContentMechanisms';
import type { TenderResponseDtoLocalContentTermsPdfUrl } from './tenderResponseDtoLocalContentTermsPdfUrl';
import type { TenderResponseDtoMaxInquiriesResponseDuration } from './tenderResponseDtoMaxInquiriesResponseDuration';
import type { TenderResponseDtoMetadata } from './tenderResponseDtoMetadata';
import type { TenderResponseDtoPublishDate } from './tenderResponseDtoPublishDate';
import type { TenderResponseDtoReferenceNumber } from './tenderResponseDtoReferenceNumber';
import type { TenderResponseDtoRegion } from './tenderResponseDtoRegion';
import type { TenderResponseDtoRemainingTimeAr } from './tenderResponseDtoRemainingTimeAr';
import type { TenderResponseDtoRemainingTimeEn } from './tenderResponseDtoRemainingTimeEn';
import type { TenderResponseDtoSector } from './tenderResponseDtoSector';
import type { TenderResponseDtoStatus } from './tenderResponseDtoStatus';
import type { TenderResponseDtoSubmissionDeadline } from './tenderResponseDtoSubmissionDeadline';
import type { TenderResponseDtoSubmissionMethodAr } from './tenderResponseDtoSubmissionMethodAr';
import type { TenderResponseDtoSubmissionMethodEn } from './tenderResponseDtoSubmissionMethodEn';
import type { TenderResponseDtoSuspensionPeriod } from './tenderResponseDtoSuspensionPeriod';
import type { TenderResponseDtoTenderActivityAr } from './tenderResponseDtoTenderActivityAr';
import type { TenderResponseDtoTenderActivityEn } from './tenderResponseDtoTenderActivityEn';
import type { TenderResponseDtoTenderNumber } from './tenderResponseDtoTenderNumber';
import type { TenderResponseDtoTenderPurposeAr } from './tenderResponseDtoTenderPurposeAr';
import type { TenderResponseDtoTenderPurposeEn } from './tenderResponseDtoTenderPurposeEn';
import type { TenderResponseDtoTenderType } from './tenderResponseDtoTenderType';
import type { TenderResponseDtoTitleEn } from './tenderResponseDtoTitleEn';
import type { TenderResponseDtoWorkStartDate } from './tenderResponseDtoWorkStartDate';

export interface TenderResponseDto {
  id: string;
  /** @nullable */
  externalId?: TenderResponseDtoExternalId;
  titleAr: string;
  /** @nullable */
  titleEn?: TenderResponseDtoTitleEn;
  /** @nullable */
  descriptionAr?: TenderResponseDtoDescriptionAr;
  /** @nullable */
  descriptionEn?: TenderResponseDtoDescriptionEn;
  /** @nullable */
  entityNameAr?: TenderResponseDtoEntityNameAr;
  /** @nullable */
  entityNameEn?: TenderResponseDtoEntityNameEn;
  /** @nullable */
  sector?: TenderResponseDtoSector;
  /** @nullable */
  region?: TenderResponseDtoRegion;
  /** @nullable */
  tenderType?: TenderResponseDtoTenderType;
  status: TenderResponseDtoStatus;
  /** @nullable */
  estimatedBudget?: TenderResponseDtoEstimatedBudget;
  /** @nullable */
  documentPrice?: TenderResponseDtoDocumentPrice;
  /** @nullable */
  submissionDeadline?: TenderResponseDtoSubmissionDeadline;
  /** @nullable */
  publishDate?: TenderResponseDtoPublishDate;
  /** @nullable */
  awardDate?: TenderResponseDtoAwardDate;
  /** @nullable */
  contractDurationMonths?: TenderResponseDtoContractDurationMonths;
  /** @nullable */
  bidCount?: TenderResponseDtoBidCount;
  source: string;
  /** RFP (كراسة شروط) PDF file URL */
  rfpFileUrl: string;
  targetSme: boolean;
  localContentRequired: boolean;
  /** @nullable */
  metadata?: TenderResponseDtoMetadata;
  tenderNumber?: TenderResponseDtoTenderNumber;
  referenceNumber?: TenderResponseDtoReferenceNumber;
  tenderPurposeAr?: TenderResponseDtoTenderPurposeAr;
  tenderPurposeEn?: TenderResponseDtoTenderPurposeEn;
  contractDurationAr?: TenderResponseDtoContractDurationAr;
  contractDurationEn?: TenderResponseDtoContractDurationEn;
  insuranceRequired?: boolean;
  governmentEntityAr?: TenderResponseDtoGovernmentEntityAr;
  governmentEntityEn?: TenderResponseDtoGovernmentEntityEn;
  competentAuthorityAr?: TenderResponseDtoCompetentAuthorityAr;
  competentAuthorityEn?: TenderResponseDtoCompetentAuthorityEn;
  remainingTimeAr?: TenderResponseDtoRemainingTimeAr;
  remainingTimeEn?: TenderResponseDtoRemainingTimeEn;
  submissionMethodAr?: TenderResponseDtoSubmissionMethodAr;
  submissionMethodEn?: TenderResponseDtoSubmissionMethodEn;
  initialGuaranteeRequired?: boolean;
  initialGuaranteeAddressAr?: TenderResponseDtoInitialGuaranteeAddressAr;
  initialGuaranteeAddressEn?: TenderResponseDtoInitialGuaranteeAddressEn;
  finalGuarantee?: TenderResponseDtoFinalGuarantee;
  inquiriesDeadline?: TenderResponseDtoInquiriesDeadline;
  bidsOpeningDate?: TenderResponseDtoBidsOpeningDate;
  bidsEvaluationDate?: TenderResponseDtoBidsEvaluationDate;
  suspensionPeriod?: TenderResponseDtoSuspensionPeriod;
  expectedAwardDate?: TenderResponseDtoExpectedAwardDate;
  workStartDate?: TenderResponseDtoWorkStartDate;
  inquiriesStartDate?: TenderResponseDtoInquiriesStartDate;
  maxInquiriesResponseDuration?: TenderResponseDtoMaxInquiriesResponseDuration;
  bidsOpeningLocationAr?: TenderResponseDtoBidsOpeningLocationAr;
  bidsOpeningLocationEn?: TenderResponseDtoBidsOpeningLocationEn;
  classifications?: TenderResponseDtoClassifications;
  executionLocationAr?: TenderResponseDtoExecutionLocationAr;
  executionLocationEn?: TenderResponseDtoExecutionLocationEn;
  detailsAr?: TenderResponseDtoDetailsAr;
  detailsEn?: TenderResponseDtoDetailsEn;
  tenderActivityAr?: TenderResponseDtoTenderActivityAr;
  tenderActivityEn?: TenderResponseDtoTenderActivityEn;
  includesSupplyItems?: boolean;
  includesConstructionWorks?: boolean;
  includesMaintenanceAndOperationWorks?: boolean;
  awardResults?: TenderResponseDtoAwardResults;
  localContentMechanisms?: TenderResponseDtoLocalContentMechanisms;
  localContentTermsPdfUrl?: TenderResponseDtoLocalContentTermsPdfUrl;
  categories: TenderCategoryResponseDto[];
  createdAt: string;
  updatedAt: string;
}
