/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { TenderCategoryResponseDtoNameEn } from './tenderCategoryResponseDtoNameEn';

export interface TenderCategoryResponseDto {
  id: string;
  nameAr: string;
  /** @nullable */
  nameEn?: TenderCategoryResponseDtoNameEn;
}
