/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type TendersControllerListTendersStatus =
  (typeof TendersControllerListTendersStatus)[keyof typeof TendersControllerListTendersStatus];

export const TendersControllerListTendersStatus = {
  open: "open",
  closed: "closed",
  under_review: "under_review",
  awarded: "awarded",
  canceled: "canceled",
} as const;
