/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { UpdateTenderDtoAwardResults } from './updateTenderDtoAwardResults';
import type { UpdateTenderDtoClassifications } from './updateTenderDtoClassifications';
import type { UpdateTenderDtoLocalContentMechanisms } from './updateTenderDtoLocalContentMechanisms';
import type { UpdateTenderDtoMetadata } from './updateTenderDtoMetadata';
import type { UpdateTenderDtoStatus } from './updateTenderDtoStatus';

export interface UpdateTenderDto {
  /** External ID of the tender */
  externalId?: string;
  /** Arabic title of the tender */
  titleAr?: string;
  /** English title of the tender */
  titleEn?: string;
  /** Arabic description of the tender */
  descriptionAr?: string;
  /** English description of the tender */
  descriptionEn?: string;
  /** Arabic entity name */
  entityNameAr?: string;
  /** English entity name */
  entityNameEn?: string;
  /** Sector of the tender */
  sector?: string;
  /** Region of the tender */
  region?: string;
  /** Tender type */
  tenderType?: string;
  /** Status of the tender */
  status?: UpdateTenderDtoStatus;
  /** Estimated budget */
  estimatedBudget?: number;
  /** Document booklet price */
  documentPrice?: number;
  /** Submission deadline (ISO Date) */
  submissionDeadline?: string;
  /** Publish date (ISO Date) */
  publishDate?: string;
  /** Contract duration in months */
  contractDurationMonths?: number;
  /** Whether the tender targets SMEs */
  targetSme?: boolean;
  /** Whether local content is required */
  localContentRequired?: boolean;
  /** Metadata JSON object */
  metadata?: UpdateTenderDtoMetadata;
  /** Tender number */
  tenderNumber?: string;
  /** Reference number */
  referenceNumber?: string;
  /** Arabic purpose of the tender */
  tenderPurposeAr?: string;
  /** English purpose of the tender */
  tenderPurposeEn?: string;
  /** Arabic contract duration */
  contractDurationAr?: string;
  /** English contract duration */
  contractDurationEn?: string;
  /** Whether insurance is required */
  insuranceRequired?: boolean;
  /** Arabic government entity name */
  governmentEntityAr?: string;
  /** English government entity name */
  governmentEntityEn?: string;
  /** Arabic competent authority name */
  competentAuthorityAr?: string;
  /** English competent authority name */
  competentAuthorityEn?: string;
  /** Arabic remaining time description */
  remainingTimeAr?: string;
  /** English remaining time description */
  remainingTimeEn?: string;
  /** Arabic offers submission method */
  submissionMethodAr?: string;
  /** English offers submission method */
  submissionMethodEn?: string;
  /** Whether initial guarantee is required */
  initialGuaranteeRequired?: boolean;
  /** Arabic initial guarantee address */
  initialGuaranteeAddressAr?: string;
  /** English initial guarantee address */
  initialGuaranteeAddressEn?: string;
  /** Final guarantee amount */
  finalGuarantee?: number;
  /** Inquiries receiving deadline (ISO Date) */
  inquiriesDeadline?: string;
  /** Bids opening date (ISO Date) */
  bidsOpeningDate?: string;
  /** Bids evaluation date (ISO Date) */
  bidsEvaluationDate?: string;
  /** Suspension period in days */
  suspensionPeriod?: number;
  /** Expected award date (ISO Date) */
  expectedAwardDate?: string;
  /** Work start date (ISO Date) */
  workStartDate?: string;
  /** Questions and inquiries sending start date (ISO Date) */
  inquiriesStartDate?: string;
  /** Max duration to answer inquiries in days */
  maxInquiriesResponseDuration?: number;
  /** Arabic bids opening location */
  bidsOpeningLocationAr?: string;
  /** English bids opening location */
  bidsOpeningLocationEn?: string;
  /** Contractors classifications list */
  classifications?: UpdateTenderDtoClassifications;
  /** Arabic execution location */
  executionLocationAr?: string;
  /** English execution location */
  executionLocationEn?: string;
  /** Arabic tender details text */
  detailsAr?: string;
  /** English tender details text */
  detailsEn?: string;
  /** Arabic tender activity */
  tenderActivityAr?: string;
  /** English tender activity */
  tenderActivityEn?: string;
  /** Whether includes supply items */
  includesSupplyItems?: boolean;
  /** Whether includes construction works */
  includesConstructionWorks?: boolean;
  /** Whether includes maintenance and operation works */
  includesMaintenanceAndOperationWorks?: boolean;
  /** Award results for packages */
  awardResults?: UpdateTenderDtoAwardResults;
  /** Local content mechanisms applied */
  localContentMechanisms?: UpdateTenderDtoLocalContentMechanisms;
  /** Local content terms PDF URL */
  localContentTermsPdfUrl?: string;
}
