/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * The preferred language of the user
 */
export type UpdateUserDtoLocale = (typeof UpdateUserDtoLocale)[keyof typeof UpdateUserDtoLocale];

export const UpdateUserDtoLocale = {
  en: "en",
  ar: "ar",
} as const;
