/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoLocale } from "./updateUserDtoLocale";

export interface UpdateUserDto {
  /** The email address of the user */
  email?: string;
  /**
   * The password of the user (min 6 characters)
   * @minLength 6
   */
  password?: string;
  /** The first name of the user */
  firstName?: string;
  /** The last name of the user */
  lastName?: string;
  /** The Google ID of the user */
  googleId?: string;
  /** Whether the user is verified */
  isVerified?: boolean;
  /** The preferred language of the user */
  locale?: UpdateUserDtoLocale;
}
