/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type UpdateProposalSectionDtoStatus =
  (typeof UpdateProposalSectionDtoStatus)[keyof typeof UpdateProposalSectionDtoStatus];

export const UpdateProposalSectionDtoStatus = {
  empty: "empty",
  generating: "generating",
  completed: "completed",
  failed: "failed",
} as const;
