/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the tender
 */
export type UpdateTenderDtoStatus = typeof UpdateTenderDtoStatus[keyof typeof UpdateTenderDtoStatus];


export const UpdateTenderDtoStatus = {
  open: 'open',
  closed: 'closed',
  under_review: 'under_review',
  awarded: 'awarded',
  canceled: 'canceled',
} as const;
