/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * Award results for packages
 */
export type UpdateTenderDtoAwardResults = { [key: string]: unknown };
