/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { UpdateProposalSectionDtoStatus } from "./updateProposalSectionDtoStatus";

export interface UpdateProposalSectionDto {
  id?: string;
  proposalId?: string;
  sectionType?: string;
  titleAr?: string;
  /** @nullable */
  titleEn?: string | null;
  /** @nullable */
  contentAr?: string | null;
  /** @nullable */
  contentEn?: string | null;
  aiGenerated?: boolean;
  humanApproved?: boolean;
  sortOrder?: number;
  status?: UpdateProposalSectionDtoStatus;
  createdAt?: string;
  updatedAt?: string;
}
