/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the user
 */
export type UserResponseDtoRole = (typeof UserResponseDtoRole)[keyof typeof UserResponseDtoRole];

export const UserResponseDtoRole = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  CUSTOMER: "CUSTOMER",
} as const;
