/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface WebhookResponseDto {
  /** Indicates if the webhook was successfully received */
  received: boolean;
}
