/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from './successResponseDto';
import type { WebhookResponseDto } from './webhookResponseDto';

export type WebhooksControllerHandleStripeWebhook200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: WebhookResponseDto;
};
