/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminDeliverProposalDto,
  AdminProposalsControllerDeliverProposal200,
  AdminProposalsControllerGetProposalDetail200,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves the complete proposal details including associated service request, organization, tender, team members, and past projects.
 * @summary Get proposal details for admin
 */
export const adminProposalsControllerGetProposalDetail = (
  id: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AdminProposalsControllerGetProposalDetail200>(
    { url: `/api/admin-api/proposals/${id}`, method: "GET", signal },
    options,
  );
};

export const getAdminProposalsControllerGetProposalDetailQueryKey = (id: string) => {
  return [`/api/admin-api/proposals/${id}`] as const;
};

export const getAdminProposalsControllerGetProposalDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminProposalsControllerGetProposalDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>
  > = ({ signal }) => adminProposalsControllerGetProposalDetail(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminProposalsControllerGetProposalDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>
>;
export type AdminProposalsControllerGetProposalDetailQueryError = void;

export function useAdminProposalsControllerGetProposalDetail<
  TData = Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
          TError,
          Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminProposalsControllerGetProposalDetail<
  TData = Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
          TError,
          Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminProposalsControllerGetProposalDetail<
  TData = Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get proposal details for admin
 */

export function useAdminProposalsControllerGetProposalDetail<
  TData = Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProposalsControllerGetProposalDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminProposalsControllerGetProposalDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Saves final updates to a proposal, marks its status as submitted, sets the associated service request to delivered, and notifies the client owner.
 * @summary Deliver / finalize a proposal
 */
export const adminProposalsControllerDeliverProposal = (
  id: string,
  adminDeliverProposalDto: AdminDeliverProposalDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AdminProposalsControllerDeliverProposal200>(
    {
      url: `/api/admin-api/proposals/${id}/deliver`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: adminDeliverProposalDto,
      signal,
    },
    options,
  );
};

export const getAdminProposalsControllerDeliverProposalMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>,
    TError,
    { id: string; data: AdminDeliverProposalDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>,
  TError,
  { id: string; data: AdminDeliverProposalDto },
  TContext
> => {
  const mutationKey = ["adminProposalsControllerDeliverProposal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>,
    { id: string; data: AdminDeliverProposalDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return adminProposalsControllerDeliverProposal(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminProposalsControllerDeliverProposalMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>
>;
export type AdminProposalsControllerDeliverProposalMutationBody = AdminDeliverProposalDto;
export type AdminProposalsControllerDeliverProposalMutationError = void;

/**
 * @summary Deliver / finalize a proposal
 */
export const useAdminProposalsControllerDeliverProposal = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>,
      TError,
      { id: string; data: AdminDeliverProposalDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminProposalsControllerDeliverProposal>>,
  TError,
  { id: string; data: AdminDeliverProposalDto },
  TContext
> => {
  return useMutation(
    getAdminProposalsControllerDeliverProposalMutationOptions(options),
    queryClient,
  );
};
